dist: xenial
language: cpp
compiler: gcc

matrix:
  include:
  - compiler: gcc
    env: BUILD_TYPE=Release
  - compiler: gcc
    env: BUILD_TYPE=Debug

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq gcc-7
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - pip install conan --user
  - conan user

script:
  - g++ --version
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg ../conanfile.py "JSONAdapter/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${BUILD_TYPE};
    else
      conan export-pkg ../conanfile.py "JSONAdapter/1.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${BUILD_TYPE};
    fi

deploy:
  provider: script
  script: conan upload "JSONAdapter/${TRAVIS_TAG:1}@systelab/stable" --all -r systelab-bintray
  on:
    tags: true
